// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    '[...all]': typeof import('./pages/[...all].vue')['default']
    '[name]': typeof import('./pages/hi/[name].vue')['default']
    404: typeof import('./layouts/404.vue')['default']
    About: typeof import('./pages/about.md')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Default: typeof import('./layouts/default.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Home: typeof import('./layouts/home.vue')['default']
    QAvatar: typeof import('quasar/src/components/avatar')['QAvatar']
    QBadge: typeof import('quasar/src/components/badge')['QBadge']
    QBtn: typeof import('quasar/src/components/btn')['QBtn']
    QDrawer: typeof import('quasar/src/components/drawer')['QDrawer']
    QFooter: typeof import('quasar')['QFooter']
    QHeader: typeof import('quasar/src/components/header')['QHeader']
    QIcon: typeof import('quasar/src/components/icon')['QIcon']
    QInput: typeof import('quasar/src/components/input')['QInput']
    QItem: typeof import('quasar/src/components/item')['QItem']
    QItemLabel: typeof import('quasar/src/components/item')['QItemLabel']
    QItemSection: typeof import('quasar/src/components/item')['QItemSection']
    QLayout: typeof import('quasar/src/components/layout')['QLayout']
    QList: typeof import('quasar/src/components/item')['QList']
    QPage: typeof import('quasar')['QPage']
    QPageContainer: typeof import('quasar/src/components/page')['QPageContainer']
    QScrollArea: typeof import('quasar/src/components/scroll-area')['QScrollArea']
    QSeparator: typeof import('quasar/src/components/separator')['QSeparator']
    QSpace: typeof import('quasar/src/components/space')['QSpace']
    QToolbar: typeof import('quasar/src/components/toolbar')['QToolbar']
    QToolbarTitle: typeof import('quasar/src/components/toolbar')['QToolbarTitle']
    QTooltip: typeof import('quasar/src/components/tooltip')['QTooltip']
    README: typeof import('./components/README.md')['default']
    RouterView: typeof import('quasar/undefined')['RouterView']
    Undefined: typeof import('./pages/index.vue')['default']
  }
}

export { }
